services:
  deepstack:
    container_name: surveillance-deepstack
    restart: unless-stopped
    image: deepquestai/deepstack
    ports:
      - '5012:5000'
    environment:
      - VISION-DETECTION=True
      - VISION-FACE=True
      - API-KEY=${DEEPSTACK_API_KEY}
    volumes:
      - /root/deepstack/models:/modelstore/detection
    networks:
      - surveillance_default
    labels:
      kuma.__docker: ""

  deepstack_ui:
    container_name: surveillance-deepstack_ui
    restart: unless-stopped
    image: robmarkcole/deepstack-ui:latest
    environment: 
      - DEEPSTACK_IP=deepstack
      - DEEPSTACK_PORT=5000
      - DEEPSTACK_API_KEY=${DEEPSTACK_API_KEY}
      - DEEPSTACK_TIMEOUT=20
      # - DEEPSTACK_CUSTOM_MODEL=fire
      - DEEPSTACK_UI_DEBUG_MODE=True
    ports:
      - '5013:8501'
    networks:
      - surveillance_default
    labels:
      kuma.__docker: ""

networks:
  surveillance_default:
    external: true