services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
    volumes:
      - /mnt/shared_configs/jellyfin/config:/config
      - /mnt/shared_configs/jellyfin/cache:/cache
      - /mnt/media/movies:/movies:ro
      - /mnt/media/tvshows:/tvshows:ro
    restart: 'unless-stopped'
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PublishedServerUrl}
      - TZ=Europe/Bratislava
    labels:
      kuma.__docker: ""
      autoheal: true      
      caddy: http://jellyfin.lan
      caddy.reverse_proxy: "{{upstreams 8096}}"   
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]    
    networks:
      - arr_default
      - caddy
      
  scheduled-restarts:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while true; do
          if [ "$$(date +'%H:%M')" = '04:00' ]; then
            docker restart jellyfin
          fi
          sleep 60
        done
        
networks:
  arr_default:
    external: true
  caddy:
    external: true        