services:

  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "8092:8080"
    volumes:
      - /root/chatgpt/open-webui:/app/backend/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - caddy
    labels:
      caddy: http://chatgpt.lan
      caddy.reverse_proxy: "{{upstreams 8080}}"
      autoheal: true
      
volumes:
  open-webui:      
networks:
  caddy:
    external: true  