GET http://localhost:8080
###
POST http://localhost:8080
Content-Type: application/json

{
    "garage_state" : "OPENING"
}
###
POST http://localhost:8080
Content-Type: application/json

{
    "garage_state" : 0
}
###
POST http://localhost:8080
Content-Type: application/json

{
    "garage_state" : "xx"
}
###
GET http://192.168.100.112:8080
###
POST http://192.168.100.112:8080
Content-Type: application/json

{
    "garage_state" : 0
}