# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/10 * * * *"

# runs the synchronisation on startup
runOnStart: true

origin:
  # url of the origin instance
  url: https://adguard.lan
  # apiPath: define an api path if other than "/control"
  insecureSkipVerify: true # disable tls check
  # cookie: Origin-Cookie-Name=CCCOOOKKKIIIEEE

# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: https://adguard2.lan
  insecureSkipVerify: true
  # cookie: Replica-Cookie-Name=CCCOOOKKKIIIEEE

# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 8081

# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true