version: "3"
services:
  gotify:
    image: gotify/server
    container_name: gotify
    ports:
      - 8091:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
    restart: unless-stopped
    volumes:
      - /root/gotify:/app/data
      - /root/gotify/config.yml:/etc/gotify/config.yml
    labels:
      kuma.__web: '"https://gotify.local/health"' 
      kuma.__docker: ""
      
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - /root/dashy/:/app/user-data/
    ports:
      - 8084:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      kuma.__web: '"https://dashy.local"'      
      kuma.__docker: ""
        
 
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:latest
    container_name: adguardhome-sync
    ports:
      - 8081:8080/tcp
    volumes:
      - /root/.adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    network_mode: bridge
    restart: unless-stopped
    labels:
      kuma.__docker: ""