services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config:/config
      - /mnt/media/frigate:/media/frigate #TODO: store the data locally, not on NAS
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5011:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD}
        
  double-take:
    container_name: double-take
    image: jakowenko/double-take:1.13.1
    restart: unless-stopped
    volumes:
      - double-take:/.storage
    ports:
      - 5014:3000
        
volumes:
  double-take:

