services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Bratislava
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://192.168.100.212:32400/
    hostname: plex.lan
    volumes:
      - /root/plex/database:/config
      - /root/plex/transcode/temp:/transcode
      - /mnt/oldmedia:/oldmedia
      - /mnt/media:/media
      - /mnt/media/movies:/movies
      - /mnt/media/tvshows:/tvshows
    labels:
      kuma.__web: '"https://plex.lan/identity"'
      kuma.__docker: ""
      
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    volumes:
      - /root/sabnzbd:/config
      - /mnt/media/downloads/sabnzbd:/downloads #optional
    ports:
      - 5003:8080
    restart: unless-stopped
    labels:
      kuma.__docker: ""
      
  komga:
    image: gotson/komga
    volumes:
      - /mnt/media/comics:/data
      - /mnt/media/downloads/komga:/downloads
      - /root/komga:/config
    ports:
      - 5002:25600
    restart: unless-stopped
    labels:
      kuma.__docker: ""
      
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Bratislava
    volumes:
      - /root/mylar3:/config
      - /mnt/media/comics:/comics
      - /mnt/downloads/comics:/downloads
      - /mnt/downloads/sabnzbd:/sabnzbddownloads
    ports:
      - 5001:8090
    restart: unless-stopped
    labels:
      kuma.__docker: ""
    
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Bratislava
    volumes:
      - /root/pyload-ng/config:/config
      - /mnt/media/downloads:/downloads
    ports:
      - 8000:8000
    restart: unless-stopped
    labels:
      kuma.__docker: ""

  sonarr:
    image: 'linuxserver/sonarr:latest'
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /root/sonarr:/config # config Folder
      - /mnt/media/tvshows:/tvshows #data Folder  
      - /mnt/media/downloads:/downloads # download folder
    ports:
      - 8989:8989
    labels:
      kuma.__docker: ""
      
  radarr:
    image: 'linuxserver/radarr:latest'
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /root/radarr:/config # config files
      - /mnt/media/movies:/movies # movies folder
      - /mnt/media/downloads:/downloads # download folder
    ports:
      - 7878:7878      
    labels:
      kuma.__docker: ""
      
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /root/prowlarr:/config
    restart: unless-stopped
    network_mode: 'service:gluetun' #comment/remove if you are not using the VPN
    depends_on:                     #comment/remove if you are not using the VPN
      - gluetun                     #comment/remove if you are not using the VPN
    labels:
      kuma.__docker: ""
      
  bazarr:
    image: 'linuxserver/bazarr:latest'
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /root/bazarr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/tvshows:/tvshows
    ports:
      - '6767:6767'
    labels:
      kuma.__docker: ""
      
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Bratislava
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /root/deluge/config:/config
      - /mnt/media/downloads:/downloads
      - /mnt/media/movies:/movies
      - /mnt/media/tvshows:/tvshows
    restart: unless-stopped
    labels:
      kuma.__docker: ""
    network_mode: 'service:gluetun' #comment/remove if you are not using the VPN
    depends_on:                     #comment/remove if you are not using the VPN
      - gluetun                     #comment/remove if you are not using the VPN
      
  gluetun:
    image: qmcgaw/gluetun:latest
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8888:8888/tcp"                         # Gluetun Local Network HTTP proxy
      - "8388:8388/tcp"                         # Gluetun Local Network Shadowsocks
      - "8388:8388/udp"                         # Gluetun Local Network Shadowsocks
      - 8112:8112   # WebUI Portal: deluge
      - "6881:6881/tcp"        # Transmission Torrent Port TCP
      - "6881:6881/udp"        # Transmission Torrent Port UDP
      - 9696:9696 #Prowlarr UI
    networks:
      default:
        aliases: # aliases so we can access deluge & prowlarr from within other containers by name
          - deluge
          - prowlarr
    volumes:
      - /root/gluetun:/gluetun
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TZ:?err}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:?err}
      - VPN_TYPE=${VPN_TYPE:?err}
      - SERVER_REGIONS=${SERVER_REGIONS:?err}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      # this will use docker DNS for containers running within gluetun (container IN gluetun network will be able to access others outside). \
      # It also potentionally leaks all DNS queries to ISP!
      - DNS_KEEP_NAMESERVER=on 
      # # prowlarr is in gluetun network. It has to access radarr/sonnarr and vice versa. Should find a better way with DNS, for now using direct IP addresses.      
      # - FIREWALL_OUTBOUND_SUBNETS=192.168.100.0/24
    labels:
      kuma.__docker: ""
      
  overseerr:
    image: sctx/overseerr:latest
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - /root/overseerr/config:/app/config
    restart: unless-stopped
    labels:
      kuma.__docker: ""    